# Slicing and Dicing Dataframes

You have seen how to do indexing of dataframes using ```df.iloc``` and ```df.loc```. Now, let's see how to subset dataframes based on certain conditions.

In [2]:
# loading libraries and reading the data
import numpy as np
import pandas as pd

df = pd.read_csv("global_sales_data/market_fact.csv")
df.head()

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

### Subsetting Rows Based on Conditions

Often, you want to select rows which satisfy some given conditions. For e.g., select all the orders where the ```Sales > 3000```, or all the orders where ```2000 < Sales < 3000``` and ```Profit < 100```.

Arguably, the best way to do these operations is using ```df.loc[]```, since ```df.iloc[]``` would require you to remember the integer column indices, which is tedious.

Let's see some examples.

In [3]:
# Select all rows where Sales > 3000
# First, we get a boolean array where True corresponds to rows having Sales > 3000
df.Sales > 3000

0       False
1       False
2        True
3       False
4        True
        ...
8394    False
8395    False
8396    False
8397     True
8398    False
Name: Sales, Length: 8399, dtype: bool

In [4]:
# Then, we pass this boolean array inside df.loc
df.loc[df.Sales > 3000]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
...,...,...,...,...,...,...,...,...,...,...
8366,Ord_3593,Prod_3,SHP_4974,Cust_1274,12073.0600,0.03,39,5081.87,19.99,0.38
8367,Ord_3593,Prod_15,SHP_4975,Cust_1274,6685.0500,0.09,25,1653.60,24.49,NaN
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28,1049.54,8.99,0.58
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62

In [13]:
# An alternative to df.Sales is df['Sales]
# You may want to put the : to indicate that you want all columns
# It is more explicit 
df.loc[df['Sales'] > 3000, :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
17,Ord_4471,Prod_15,SHP_6228,Cust_1521,13255.9300,0.02,25,4089.27,26.00,0.60
22,Ord_996,Prod_5,SHP_1377,Cust_371,3202.2500,0.09,44,991.26,19.99,0.43
28,Ord_2573,Prod_4,SHP_3527,Cust_931,3594.7435,0.05,38,1016.97,2.50,0.55
40,Ord_5035,Prod_15,SHP_7024,Cust_1710,4917.6900,0.02,42,126.31,30.00,0.71
57,Ord_4546,Prod_1,SHP_6327,Cust_1474,5208.7800,0.05,34,1547.78,7.07,0.59
64,Ord_4475,Prod_4,SHP_6234,Cust_1474,7640.2250,0.07,46,2027.68,2.50,0.59
79,Ord_5188,Prod_14,SHP_7252,Cust_1749,5177.4000,0.06,12,287.50,49.00,0.38
82,Ord_5156,Prod_4,SHP_7207,Cust_1749,8374.1320,0.06,48,2568.10,8.99,0.56
84,Ord_5232,Prod_17,SHP_7306,Cust_1758,21366.5100,0.00,3,-11984.40,24.49,0.39
107,Ord_250,Prod_15,SHP_346,Cust_45,8901.7800,0.04,31,2795.36,24.49,NaN
121,Ord_5423,Prod_17,SHP_7577,Cust_1800,13070.2000,0.07,4,-6923.60,8.73,0.57
124,Ord_2432,Prod_4,SHP_3339,Cust_933,3883.4715,0.10,42,707.17,8.99,0.58
133,Ord_2432,Prod_3,SHP_3338,Cust_933,15337.5800,0.10,30,6670.41,19.99,0.37
148,Ord_1649,Prod_2,SHP_2277,Cust_498,3005.7400,0.02,48,1053.21,3.99,0.57
163,Ord_4646,Prod_15,SHP_6475,Cust_1603,4083.1900,0.07,43,-1049.85,45.00,0.69
164,Ord_4646,Prod_1,SHP_6476,Cust_1603,4902.3800,0.05,32,1438.49,7.07,0.59
165,Ord_4702,Prod_3,SHP_6560,Cust_1603,11823.5200,0.10,34,4592.74,19.99,0.40
168,Ord_2973,Prod_4,SHP_4102,Cust_1081,4671.1495,0.07,28,947.31,4.20,0.59
169,Ord_3009,Prod_15,SHP_4168,Cust_1081,5718.8500,0.09,49,-2426.55,70.20,0.74
170,Ord_2973,Prod_4,SHP_4102,Cust_1480,6264.1855,0.01,34,1312.04,19.99,0.60
171,Ord_2973,Prod_9,SHP_6073,Cust_1480,5410.9500,0.09,36,2077.91,19.99,0.39
183,Ord_5157,Prod_15,SHP_7208,Cust_1753,5149.0600,0.03,27,605.44,30.00,0.69
185,Ord_5153,Prod_11,SHP_7202,Cust_1753,3457.5600,0.02,35,-365.44,51.94,0.63
189,Ord_2831,Prod_3,SHP_3893,Cust_1036,18092.6600,0.09,36,7917.76,19.99,0.37
191,Ord_2791,Prod_11,SHP_3838,Cust_1036,10351.0100,0.08,19,-1331.55,45.70,0.71
...,...,...,...,...,...,...,...,...,...,...
8125,Ord_4515,Prod_1,SHP_6285,Cust_1546,4976.6000,0.06,32,601.88,19.99,0.66
8137,Ord_2267,Prod_2,SHP_3089,Cust_890,6608.2400,0.09,35,2164.64,0.99,0.55
8141,Ord_3368,Prod_15,SHP_4668,Cust_1190,3227.3800,0.05,26,192.31,30.00,0.64
8143,Ord_3265,Prod_1,SHP_4530,Cust_1190,10330.9400,0.07,25,2914.56,19.99,0.58
8151,Ord_3214,Prod_2,SHP_4456,Cust_1187,8316.7600,0.05,30,2108.80,23.19,0.59
8158,Ord_2868,Prod_15,SHP_3950,Cust_1059,5405.4400,0.07,18,604.46,64.73,0.56
8207,Ord_3433,Prod_8,SHP_4759,Cust_1180,3601.0700,0.04,50,174.80,14.52,0.65
8210,Ord_2110,Prod_17,SHP_2885,Cust_802,4502.2600,0.09,38,1272.17,26.30,0.38
8211,Ord_2144,Prod_1,SHP_2925,Cust_802,5318.8900,0.06,48,525.15,8.64,0.78
8217,Ord_3359,Prod_10,SHP_7245,Cust_1762,28389.1400,0.07,33,7132.18,44.55,0.62
8219,Ord_5200,Prod_4,SHP_7266,Cust_1762,4815.8620,0.08,47,1316.79,4.20,0.57
8235,Ord_759,Prod_5,SHP_1036,Cust_245,8549.0400,0.03,42,2861.01,11.54,0.59
8240,Ord_793,Prod_11,SHP_1090,Cust_245,4452.6500,0.09,30,-265.12,60.00,0.55
8249,Ord_3470,Prod_17,SHP_4805,Cust_1203,5615.4000,0.07,46,1807.16,26.30,0.38
8263,Ord_4954,Prod_15,SHP_6913,Cust_1694,7987.4300,0.03,49,1304.90,30.00,0.62
8283,Ord_1741,Prod_11,SHP_2411,Cust_595,15168.8200,0.02,26,-1096.78,147.12,0.80
8286,Ord_1749,Prod_1,SHP_2424,Cust_595,5176.2700,0.01,38,-743.45,35.00,0.84
8292,Ord_1765,Prod_14,SHP_2446,Cust_595,14647.2600,0.07,25,5485.15,24.49,0.37
8298,Ord_2172,Prod_1,SHP_2960,Cust_787,6648.5800,0.08,19,-555.98,99.00,0.65
8308,Ord_2659,Prod_8,SHP_3638,Cust_1016,4744.6400,0.04,46,1033.38,19.99,0.52
8317,Ord_2770,Prod_3,SHP_3802,Cust_1016,7535.9600,0.08,46,2745.87,19.99,0.40
8329,Ord_2160,Prod_15,SHP_2944,Cust_810,3636.3700,0.06,33,-176.91,30.00,0.69
8332,Ord_2101,Prod_11,SHP_2875,Cust_790,10714.7800,0.00,41,-627.64,66.67,0.65
8335,Ord_2070,Prod_11,SHP_2833,Cust_784,3905.7500,0.01,21,55.30,29.21,0.76
8343,Ord_2178,Prod_4,SHP_2968,Cust_785,6030.5800,0.09,39,1197.86,8.99,0.58
8366,Ord_3593,Prod_3,SHP_4974,Cust_1274,12073.0600,0.03,39,5081.87,19.99,0.38
8367,Ord_3593,Prod_15,SHP_4975,Cust_1274,6685.0500,0.09,25,1653.60,24.49,NaN
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28,1049.54,8.99,0.58
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62

In [5]:
# We combine multiple conditions using the & operator
# E.g. all orders having 2000 < Sales < 3000 and Profit > 100
df.loc[(df.Sales > 2000) & (df.Sales < 3000) & (df.Profit > 100), :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
81,Ord_5205,Prod_4,SHP_7274,Cust_1749,2546.5235,0.09,26,210.00,7.69,0.59
109,Ord_139,Prod_17,SHP_186,Cust_45,2671.2100,0.06,14,636.18,15.59,0.36
110,Ord_239,Prod_4,SHP_332,Cust_45,2157.3085,0.00,38,519.25,5.31,0.57
141,Ord_1673,Prod_17,SHP_2314,Cust_498,2027.5500,0.04,14,537.40,13.99,0.37
...,...,...,...,...,...,...,...,...,...,...
8338,Ord_2107,Prod_2,SHP_2882,Cust_785,2409.9600,0.07,32,575.10,4.50,0.59
8350,Ord_3570,Prod_4,SHP_4942,Cust_1266,2094.9780,0.06,44,697.29,1.25,0.55
8354,Ord_3592,Prod_4,SHP_4973,Cust_1266,2614.3705,0.07,25,384.01,7.69,0.58
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25,561.13,8.99,0.59
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59

In [15]:
# The 'OR' operator is represented by a | (Note that 'or' doesn't work with pandas)
# E.g. all orders having 2000 < Sales  OR Profit > 100
df.loc[(df.Sales > 2000) | (df.Profit > 100), :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
16,Ord_2282,Prod_9,SHP_3122,Cust_839,443.4600,0.06,30,193.12,1.39,0.38
17,Ord_4471,Prod_15,SHP_6228,Cust_1521,13255.9300,0.02,25,4089.27,26.00,0.60
22,Ord_996,Prod_5,SHP_1377,Cust_371,3202.2500,0.09,44,991.26,19.99,0.43
27,Ord_2405,Prod_9,SHP_3300,Cust_931,1062.6900,0.01,28,401.80,6.66,0.40
28,Ord_2573,Prod_4,SHP_3527,Cust_931,3594.7435,0.05,38,1016.97,2.50,0.55
37,Ord_5040,Prod_2,SHP_7032,Cust_1710,1637.7800,0.08,38,461.65,4.62,0.56
38,Ord_5035,Prod_12,SHP_7025,Cust_1710,416.8000,0.01,32,223.38,0.50,0.38
39,Ord_5045,Prod_5,SHP_7040,Cust_1710,1286.8700,0.05,48,384.38,6.93,0.49
40,Ord_5035,Prod_15,SHP_7024,Cust_1710,4917.6900,0.02,42,126.31,30.00,0.71
47,Ord_4659,Prod_6,SHP_6493,Cust_1579,1451.5900,0.06,26,435.11,14.30,0.37
54,Ord_4682,Prod_4,SHP_6531,Cust_1579,1909.0065,0.01,32,344.13,8.99,0.59
56,Ord_4410,Prod_5,SHP_6146,Cust_1474,605.7700,0.05,42,129.33,5.00,0.49
57,Ord_4546,Prod_1,SHP_6327,Cust_1474,5208.7800,0.05,34,1547.78,7.07,0.59
62,Ord_4410,Prod_6,SHP_6146,Cust_1474,1480.9100,0.00,44,489.14,8.74,0.40
64,Ord_4475,Prod_4,SHP_6234,Cust_1474,7640.2250,0.07,46,2027.68,2.50,0.59
70,Ord_4607,Prod_2,SHP_6408,Cust_1474,1463.4200,0.08,26,350.82,3.99,0.57
77,Ord_5213,Prod_13,SHP_7284,Cust_1749,1633.3700,0.08,50,144.69,7.73,0.59
79,Ord_5188,Prod_14,SHP_7252,Cust_1749,5177.4000,0.06,12,287.50,49.00,0.38
81,Ord_5205,Prod_4,SHP_7274,Cust_1749,2546.5235,0.09,26,210.00,7.69,0.59
82,Ord_5156,Prod_4,SHP_7207,Cust_1749,8374.1320,0.06,48,2568.10,8.99,0.56
84,Ord_5232,Prod_17,SHP_7306,Cust_1758,21366.5100,0.00,3,-11984.40,24.49,0.39
88,Ord_5172,Prod_4,SHP_7229,Cust_1758,1239.4445,0.07,22,165.50,3.99,0.59
98,Ord_5481,Prod_15,SHP_7659,Cust_1820,2700.7800,0.06,29,-793.36,58.20,0.58
102,Ord_1557,Prod_2,SHP_2152,Cust_565,1736.5300,0.10,46,457.03,3.99,0.56
...,...,...,...,...,...,...,...,...,...,...
8328,Ord_2169,Prod_6,SHP_2956,Cust_810,1321.5500,0.10,25,448.24,10.75,0.36
8329,Ord_2160,Prod_15,SHP_2944,Cust_810,3636.3700,0.06,33,-176.91,30.00,0.69
8331,Ord_2148,Prod_10,SHP_2929,Cust_810,2966.1300,0.08,31,-1456.31,57.38,0.78
8332,Ord_2101,Prod_11,SHP_2875,Cust_790,10714.7800,0.00,41,-627.64,66.67,0.65
8334,Ord_2124,Prod_3,SHP_2900,Cust_790,926.8500,0.09,34,382.94,1.49,0.38
8335,Ord_2070,Prod_11,SHP_2833,Cust_784,3905.7500,0.01,21,55.30,29.21,0.76
8338,Ord_2107,Prod_2,SHP_2882,Cust_785,2409.9600,0.07,32,575.10,4.50,0.59
8342,Ord_2119,Prod_2,SHP_2895,Cust_785,1623.0900,0.02,28,245.88,13.22,0.56
8343,Ord_2178,Prod_4,SHP_2968,Cust_785,6030.5800,0.09,39,1197.86,8.99,0.58
8344,Ord_2194,Prod_5,SHP_2991,Cust_785,525.7800,0.03,20,180.64,6.93,0.49
8347,Ord_3534,Prod_4,SHP_4894,Cust_1266,1735.3515,0.08,31,258.62,8.99,0.56
8350,Ord_3570,Prod_4,SHP_4942,Cust_1266,2094.9780,0.06,44,697.29,1.25,0.55
8351,Ord_3584,Prod_15,SHP_4961,Cust_1266,2502.6700,0.10,9,-198.80,64.73,0.56
8354,Ord_3592,Prod_4,SHP_4973,Cust_1266,2614.3705,0.07,25,384.01,7.69,0.58
8358,Ord_3582,Prod_6,SHP_4959,Cust_1266,539.6600,0.00,26,147.08,5.97,0.38
8359,Ord_3543,Prod_3,SHP_4906,Cust_1266,514.2200,0.02,17,187.37,2.99,0.35
8360,Ord_3639,Prod_10,SHP_5038,Cust_1266,2173.2600,0.00,35,-465.66,36.61,0.61
8362,Ord_3593,Prod_5,SHP_4975,Cust_1274,1175.5300,0.03,18,257.59,14.48,0.46
8366,Ord_3593,Prod_3,SHP_4974,Cust_1274,12073.0600,0.03,39,5081.87,19.99,0.38
8367,Ord_3593,Prod_15,SHP_4975,Cust_1274,6685.0500,0.09,25,1653.60,24.49,NaN
8369,Ord_3633,Prod_3,SHP_5031,Cust_1274,1169.2600,0.02,41,515.62,1.49,0.38
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28,1049.54,8.99,0.58
8375,Ord_2772,Prod_3,SHP_3806,Cust_1006,1413.8200,0.10,47,226.53,11.63,0.37
8378,Ord_2706,Prod_2,SHP_3705,Cust_1006,1361.9100,0.05,20,312.52,3.50,0.59
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25,561.13,8.99,0.59
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85
8385,Ord_1833,Prod_3,SHP_2527,Cust_637,611.1600,0.04,46,100.22,4.98,0.40
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [6]:
# E.g. all orders having 2000 < Sales < 3000 and Profit > 100
# Also, this time, you only need the Cust_id, Sales and Profit columns
df.loc[(df.Sales > 2000) & (df.Sales < 3000) & (df.Profit > 100), ['Cust_id', 'Sales', 'Profit']]

        Cust_id      Sales  Profit
3     Cust_1818  2337.8900  729.34
81    Cust_1749  2546.5235  210.00
109     Cust_45  2671.2100  636.18
110     Cust_45  2157.3085  519.25
141    Cust_498  2027.5500  537.40
...         ...        ...     ...
8338   Cust_785  2409.9600  575.10
8350  Cust_1266  2094.9780  697.29
8354  Cust_1266  2614.3705  384.01
8381  Cust_1006  2836.0505  561.13
8394  Cust_1798  2841.4395  374.63

[328 rows x 3 columns]

In [17]:
# You can use the == and != operators 
df.loc[(df.Sales == 4233.15), :]
df.loc[(df.Sales != 1000), :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33,45.84,0.71,0.52
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.2200,0.07,8,-27.72,6.60,0.37
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
11,Ord_1925,Prod_6,SHP_2637,Cust_708,465.9000,0.05,38,79.34,4.86,0.38
12,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.0500,0.04,27,23.12,3.37,0.57
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.9300,0.08,10,-317.48,36.09,0.77
15,Ord_2280,Prod_5,SHP_3114,Cust_839,460.6900,0.06,48,-103.48,7.29,0.45
16,Ord_2282,Prod_9,SHP_3122,Cust_839,443.4600,0.06,30,193.12,1.39,0.38
17,Ord_4471,Prod_15,SHP_6228,Cust_1521,13255.9300,0.02,25,4089.27,26.00,0.60
18,Ord_4427,Prod_6,SHP_6171,Cust_1521,283.1300,0.08,45,-141.26,6.81,0.36
19,Ord_996,Prod_13,SHP_1378,Cust_371,41.9700,0.05,12,-37.03,4.20,0.56
20,Ord_996,Prod_13,SHP_1378,Cust_371,57.1700,0.08,18,-24.03,2.31,0.56
21,Ord_996,Prod_6,SHP_1378,Cust_371,81.2500,0.01,11,-44.54,7.86,0.37
22,Ord_996,Prod_5,SHP_1377,Cust_371,3202.2500,0.09,44,991.26,19.99,0.43
23,Ord_996,Prod_7,SHP_1378,Cust_371,35.6400,0.05,10,-0.71,1.63,0.36
24,Ord_2573,Prod_3,SHP_3525,Cust_931,197.6100,0.08,13,3.46,7.27,0.38
25,Ord_2335,Prod_13,SHP_3204,Cust_931,38.2600,0.03,22,-2.34,0.70,0.56
26,Ord_2456,Prod_5,SHP_3367,Cust_931,109.5800,0.00,13,31.32,4.00,0.42
27,Ord_2405,Prod_9,SHP_3300,Cust_931,1062.6900,0.01,28,401.80,6.66,0.40
28,Ord_2573,Prod_4,SHP_3527,Cust_931,3594.7435,0.05,38,1016.97,2.50,0.55
29,Ord_2478,Prod_12,SHP_3395,Cust_931,139.9800,0.07,33,-140.54,6.89,0.39
...,...,...,...,...,...,...,...,...,...,...
8369,Ord_3633,Prod_3,SHP_5031,Cust_1274,1169.2600,0.02,41,515.62,1.49,0.38
8370,Ord_2696,Prod_13,SHP_3690,Cust_1006,62.7800,0.04,20,-17.75,2.03,0.57
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28,1049.54,8.99,0.58
8372,Ord_2772,Prod_9,SHP_3806,Cust_1006,56.9000,0.03,7,12.64,1.39,0.36
8373,Ord_2600,Prod_16,SHP_3560,Cust_1006,106.6400,0.10,30,-31.95,1.32,0.83
8374,Ord_2658,Prod_5,SHP_3637,Cust_1006,1082.6600,0.08,14,-256.93,48.20,0.74
8375,Ord_2772,Prod_3,SHP_3806,Cust_1006,1413.8200,0.10,47,226.53,11.63,0.37
8376,Ord_2624,Prod_8,SHP_3590,Cust_1006,1211.0000,0.00,36,-27.99,6.50,0.79
8377,Ord_2722,Prod_12,SHP_3729,Cust_1006,34.0100,0.00,12,10.58,0.50,0.39
8378,Ord_2706,Prod_2,SHP_3705,Cust_1006,1361.9100,0.05,20,312.52,3.50,0.59
8379,Ord_2722,Prod_5,SHP_3730,Cust_1006,1008.9500,0.04,41,69.31,8.99,0.50
8380,Ord_2772,Prod_6,SHP_3807,Cust_1006,308.9200,0.04,45,-143.58,7.37,0.37
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25,561.13,8.99,0.59
8382,Ord_2658,Prod_3,SHP_3636,Cust_1006,120.9800,0.00,28,-92.85,5.34,0.38
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85
8384,Ord_4620,Prod_3,SHP_6435,Cust_1577,59.6200,0.04,10,-56.30,7.78,0.37
8385,Ord_1833,Prod_3,SHP_2527,Cust_637,611.1600,0.04,46,100.22,4.98,0.40
8386,Ord_2324,Prod_7,SHP_3189,Cust_851,121.8700,0.07,39,11.32,1.35,0.40
8387,Ord_2220,Prod_3,SHP_3019,Cust_851,41.0600,0.04,4,-16.39,6.28,0.35
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.0400,0.03,10,-335.06,35.00,NaN
8389,Ord_4444,Prod_13,SHP_6192,Cust_1519,159.4100,0.00,44,34.68,0.98,0.52
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,316.9900,0.04,47,-276.54,8.37,0.58
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,1991.8985,0.07,20,88.36,7.69,0.58
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,181.5000,0.08,43,-6.24,2.50,0.37
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,356.7200,0.07,9,12.61,1.99,0.44
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [18]:
# You may want to select rows whose column value is in an iterable
# For instance, say a colleague gives you a list of customer_ids from a certain region

customers_in_bangalore = ['Cust_1798', 'Cust_1519', 'Cust_637', 'Cust_851']

# To get all the orders from these customers, use the isin() function
# It returns a boolean, which you can use to select rows
df.loc[df['Cust_id'].isin(customers_in_bangalore), :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
8385,Ord_1833,Prod_3,SHP_2527,Cust_637,611.1600,0.04,46,100.22,4.98,0.40
8386,Ord_2324,Prod_7,SHP_3189,Cust_851,121.8700,0.07,39,11.32,1.35,0.40
8387,Ord_2220,Prod_3,SHP_3019,Cust_851,41.0600,0.04,4,-16.39,6.28,0.35
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.0400,0.03,10,-335.06,35.00,NaN
8389,Ord_4444,Prod_13,SHP_6192,Cust_1519,159.4100,0.00,44,34.68,0.98,0.52
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,316.9900,0.04,47,-276.54,8.37,0.58
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,1991.8985,0.07,20,88.36,7.69,0.58
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,181.5000,0.08,43,-6.24,2.50,0.37
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,356.7200,0.07,9,12.61,1.99,0.44
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38